### ISSUE TITLE
Problem when decompress compressed.bin

### ISSUE THREAD

**Issue by alordred** [tensorflow/compression#18] opened 2019-04-20 03:27 UTC
enviroment: 
tensorflow1.13 cuda10 compression-1.1

lee@home:~/HungSheng/end2EndCompression/compression-1.1/examples$ python bls2017.py decompress compressed.bin reconstruction.png
WARNING:tensorflow:From /home/lee/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "bls2017.py", line 338, in <module>
    decompress()
  File "bls2017.py", line 267, in decompress
    x_hat = x_hat[0, :x_shape[0], :x_shape[1], :]
  File "/home/lee/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 597, in _slice_helper
    _check_index(s.stop)
  File "/home/lee/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 516, in _check_index
    raise TypeError(_SLICE_TYPE_ERROR + ", got {!r}".format(idx))
TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got 756

**Comment by jonycgn** [comment] 2019-04-22 02:16
Hi alordred,

this looks like a change in TensorFlow that we didn‘t notice. Please open bls2017.py and change line 262, so that it reads:

x_hat = x_hat[0, :int(x_shape[0]), :int(x_shape[1]), :]

Let us know if this fixed it.

Best,
Johannes

**Comment by ZhangDkzzzzz** [comment] 2019-04-24 09:11
enviroment:
tensorflow1.13 cuda10 compression-1.2b
I succeeded in solving alordred's problem by replacing with x_hat = x_hat[0, :int(x_shape[0]), :int(x_shape[1]), :] ,but then I had a new problen.

My Full Trace is Below:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key synthesis/layer_0/signal_conv2d/bias not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key synthesis/layer_0/signal_conv2d/bias not found in checkpoint
         [[node save/RestoreV2 (defined at bls2017.py:271) ]]

Caused by op 'save/RestoreV2', defined at:
  File "bls2017.py", line 334, in <module>
    decompress()
  File "bls2017.py", line 271, in decompress
    tf.train.Saver().restore(sess, save_path=latest)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key synthesis/layer_0/signal_conv2d/bias not found in checkpoint
         [[node save/RestoreV2 (defined at bls2017.py:271) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1591, in object_graph_key_mapping
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 370, in get_tensor
    status)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bls2017.py", line 334, in <module>
    decompress()
  File "bls2017.py", line 271, in decompress
    tf.train.Saver().restore(sess, save_path=latest)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1292, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key synthesis/layer_0/signal_conv2d/bias not found in checkpoint
         [[node save/RestoreV2 (defined at bls2017.py:271) ]]

Caused by op 'save/RestoreV2', defined at:
  File "bls2017.py", line 334, in <module>
    decompress()
  File "bls2017.py", line 271, in decompress
    tf.train.Saver().restore(sess, save_path=latest)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/root/miniconda3/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key synthesis/layer_0/signal_conv2d/bias not found in checkpoint
         [[node save/RestoreV2 (defined at bls2017.py:271) ]]

Is something wrong with the bias variable’ name？

**Comment by jonycgn** [comment] 2019-04-24 20:07
Hello,

please try to delete your checkpoint directory and try again. It looks like you have changed the code, but are trying to train with an older checkpoint.

**Comment by grenki** [comment] 2019-04-25 22:20
@ZhangDkzzzzz  Same problem.
Check my repo for fast fix. Sorry for unclear code )
https://github.com/grenki/compression/commit/234731cafdea3c9ad50ba870149bc1d6b596f166

**Comment by jonycgn** [comment] 2019-04-26 01:22
@grenki Thanks for providing this patch.
@ZhangDkzzzzz could you make it work?

In principle, it shouldn’t be necessary to restore the analysis transform to decompress. But there may be some issue/regression in the way name scopes are handled in TensorFlow. I’m currently out of office, but will look into it when I’m back.

(For 1.2, we’re going to refactor this code to use tf.Estimator. This should also take care of these issues.)

**Comment by ZhangDkzzzzz** [comment] 2019-04-27 10:51
@grenki @jonycgn  thanx for the fast repo,it works.
I extract my checkpoint's variables name :

tensor_name:  synthesis/layer_0/signal_conv2d_3/gdn_2/reparam_beta
tensor_name:  synthesis/layer_0/signal_conv2d_3/kernel_rdft/Adam
tensor_name:  synthesis/layer_0/signal_conv2d_3/bias/Adam_1
tensor_name:  synthesis/layer_0/signal_conv2d_3/gdn_2/reparam_gamma/Adam
tensor_name:  synthesis/layer_0/signal_conv2d_3/gdn_2/reparam_beta/Adam_1

but when I run the decompress(),the variables name:

synthesis/layer_0/signal_conv2d/kernel_rdft:0
synthesis/layer_0/signal_conv2d/bias:0
synthesis/layer_0/signal_conv2d/gdn/reparam_beta:0
synthesis/layer_0/signal_conv2d/gdn/reparam_gamma:0

see synthesis/layer_0/signal_conv2d/XX add "_2"
The cause of the problem seems to be running compression( ) while running  decompress( ) during train( ), thus lead to namescope conflict.

**Comment by jonycgn** [comment] 2019-07-19 18:17
Hi, sorry for the delay. Try adding this code at line 251:

analysis_transform(tf.placeholder(tf.float32, (1, None, None, 3)), args.num_filters)

This should fix it for now.

**Comment by jonycgn** [comment] 2019-07-19 20:49
Closing this, please reopen if the problem still exists.

**Closed by jonycgn** 2019-07-19 20:49 UTC
