### ISSUE TITLE
Untraced functions problem

### ISSUE THREAD

**Issue by nguerinjr** [tensorflow/compression#72] opened 2021-03-11 19:10 UTC
Hello @jonycgn.

I am testing the new version based on the tf-nightly. That specific error issue while saving is not happening anymore, that's why I am opening a separate issue. The use case is still the bls2017 code.

I am using python 3.8.8 and the tf-nightly version is
> tf-estimator-nightly==2.5.0.dev2021031101
> tf-nightly==2.5.0.dev20210311

The current version of the code apparently has some tracing problems while saving the model with the `model.save()` function.

> W0311 15:25:34.421833 139634614691648 save.py:235] Found untraced functions such as lambda_layer_call_fn, layer_0_layer_call_fn, layer_1_layer_call_fn, layer_2_layer_call_fn, layer_0_layer_call_fn while saving (showing 5 of 36). These functions will not be directly callable after loading.

I did not investigate it yet, therefore I do not know if it is a problem actually or something that can be ignored.

Interestingly, I have tried again, for the sake of comparison, the `tf.keras.callbacks.ModelCheckpoint` . I don't know if it is something related to the changes in TF 2.5 that you have mentioned, but using this code

![Captura de tela 2021-03-10 213457](https://user-images.githubusercontent.com/35977339/110838104-d7084400-8280-11eb-8508-727f2c2031c9.png)

It gives me the following stack error:

> Traceback (most recent call last):
  File "/home/nguerinjr/Documents/projects/deep_image_compression/balle.py", line 467, in <module>
    app.run(main, flags_parser=parse_args)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/nguerinjr/Documents/projects/deep_image_compression/balle.py", line 455, in main
    train(args)
  File "/home/nguerinjr/Documents/projects/deep_image_compression/balle.py", line 273, in train
    model.fit(
  File "/home/nguerinjr/Documents/projects/deep_image_compression/balle.py", line 178, in fit
    retval = super().fit(*args, **kwargs)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1203, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 432, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 1357, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 1421, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2080, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 157, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 92, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1085, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def,
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1272, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def,
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1202, in _build_meta_graph_impl
    saveable_view = _SaveableView(checkpoint_graph_view, options,
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 188, in __init__
    self._trace_all_concrete_functions()
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 274, in _trace_all_concrete_functions
    function._list_all_concrete_functions_for_serialization()  # pylint: disable=protected-access
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1208, in _list_all_concrete_functions_for_serialization
    concrete_functions = self._list_all_concrete_functions()
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1190, in _list_all_concrete_functions
    self.get_concrete_function()
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1345, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1251, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 748, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3045, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3439, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3274, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 998, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 657, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3966, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/nguerinjr/anaconda3/envs/tf-nightly/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 985, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /home/nguerinjr/Documents/projects/deep_image_compression/balle.py:196 compress  *
        return self.entropy_model.compress(y), x_shape, y_shape

    AttributeError: 'BLS2017Model' object has no attribute 'entropy_model'

Looking at the stack, the `tf.keras.callbacks.ModelCheckpoint` calls the `model.save()` internally. 

![Captura de tela 2021-03-11 154912](https://user-images.githubusercontent.com/35977339/110838817-ad9be800-8281-11eb-9d12-feef688cbf50.png)

But it this case, seems like the  `super().fit(*args, **kwargs)` has not finished yet, so the `self.entropy_model = tfc.ContinuousBatchedEntropyModel(self.prior, coding_rank=3, compression=True)` was not accessed, which causes some problems in the saving of the model, as the field `self.entropy_model` does not exist . I don't know if it is something to concern about, but it apparently restricts the use of this specific callback.

There are more incompatibilities with the callback. Even though this error occurs, when I run again, it prints the following type of warnings (I put just some of them):

> ved object in checkpoint: (root).model.optimizer.iter
W0311 15:59:40.661861 140151146448704 util.py:160] Unresolved object in checkpoint: (root).model.optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.optimizer.learning_rate
W0311 15:59:40.662101 140151146448704 util.py:160] Unresolved object in checkpoint: (root).model.optimizer.learning_rate

> W0311 15:59:40.662257 140151146448704 util.py:160] Unresolved object in checkpoint: (root).model.optimizer's state 'm' for (root).model.synthesis_transform.layer_with_weights-1._bias_parameter
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.optimizer's state 'm' for (root).model.synthesis_transform.layer_with_weights-2._bias_parameter

> ved object in checkpoint: (root).model.optimizer's state 'v' for (root).model.synthesis_transform.layer_with_weights-2._bias_parameter
W0311 15:59:40.663180 140151146448704 util.py:160] Unresolved object in checkpoint: (root).model.optimizer's state 'v' for (root).model.synthesis_transform.layer_with_weights-2._bias_parameter
WARNING:tensorflow:Unresolved object in checkpoint: (root).model.optimizer's state 'v' for (root).model.analysis_transform.layer_with_weights-0._kernel_parameter.rdft

I was interested to see which checkpoint it is using since the execution of the code raised an error. But it seems like it gets this checkpoint from the `chief` folder:
![Captura de tela 2021-03-11 155827](https://user-images.githubusercontent.com/35977339/110840638-bbeb0380-8283-11eb-9693-f826e0f92f8e.png)
![Captura de tela 2021-03-11 155845](https://user-images.githubusercontent.com/35977339/110840647-bee5f400-8283-11eb-9d8b-d1352aa5dad8.png)

Which I suppose, is the folder generated by `tf.keras.callbacks.experimental.BackupAndRestore` (only a supposition since I do not know this callback thoroughly yet). If it is the case, there is an incompatibility between these two callbacks. 

These are the new issues I have found investigating the new version further.

**Comment by jonycgn** [comment] 2021-03-11 19:16
Hi @nguerinjr, I think the untraced functions message can be ignored. Have you tried just compressing and decompressing an image with the checked-in code?

**Comment by nguerinjr** [comment] 2021-03-11 20:33
I performed a fast overfitting of the checked-in code and it seems ok. The model works in compressing and decompressing the image.

There are a bunch of warnings related to the custom gradients of your code
> W0311 16:54:55.336309 140616504092480 function_deserialization.py:500] Importing a function (__inference_analysis_layer_call_and_return_conditional_losses_88486) with ops with custom gradients. Will likely fail if a gradient is requested.
W0311 16:54:55.357203 140616504092480 function_deserialization.py:500] Importing a function (__inference_layer_1_layer_call_and_return_conditional_losses_90596) with ops with custom gradients. Will likely fail if a gradient is requested.

But it seems like they are not something that causes problems since gradients are not computed in inference time. I don't know if  it would case a problem when continue training a model. I have not tested it.

I performed additional observations on the load problem I related earlier, while using the `chief` folder. Actually, this specific problem is not related to the `tf.keras.callbacks.ModelCheckpoint`. This checkpoint only raises the error related to the field `self.entropy_model`.

I performed the following steps. I used the code with the ModelCheckpoint to interrupt the training, raising that exception, so the `chief` folder appears.

![Captura de tela 2021-03-11 171158](https://user-images.githubusercontent.com/35977339/110848528-f7d69680-828c-11eb-928d-41c0456ac767.png)

To isolate the problem, I commented the ModelCheckpoint line and run again the training code increasing the number of desired iterations (since it stopped in the last iterations, so the fit would not run anything)

![Captura de tela 2021-03-11 171133](https://user-images.githubusercontent.com/35977339/110848634-15a3fb80-828d-11eb-8a43-a6fca03e0457.png)

The first thing is that it does not continue training in this case. It simply ignored the additional steps in the second run. When the `model.save()` is executed, it triggers the warnings I have reported earlier:

> WARNING:tensorflow:Unresolved object in checkpoint: (root).model.optimizer's state 'v' for (root).model.synthesis_transform.layer_with_weights-1._activation._gamma_parameter.variable
W0311 17:17:57.030321 140329214723904 util.py:160] Unresolved object in checkpoint: (root).model.optimizer's state 'v' for (root).model.synthesis_transform.layer_with_weights-1._activation._gamma_parameter.variable
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
W0311 17:17:57.030352 140329214723904 util.py:168] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.

But I think it is related to the fact that the fit did not run, since the exception is the following:
> ValueError: Model <__main__.BLS2017Model object at 0x7ff5e2ec5d00> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`.

So maybe there are two problems. One of them related to the use of the `ModelCheckpoint ` callback. The other one is related to the continuation of the training when it was interrupted.

**Comment by jonycgn** [comment] 2021-03-11 21:07
Hi, I just tried out training the model in the current version.

Continuation of training after it was interrupted works for me. The checkpoints are written by the BackupAndRestore callback after every epoch of training. So if you interrupt the training, it will be continued at the beginning of the incomplete epoch. Presumably you can coerce the model to keep training by increasing the number of epochs (but not the number of steps per epoch, since the epoch count is what matters for the continuation logic).

I also confirmed that compression and decompression works after training is completed.

Note that the current code for compression/decompression assumes that the model was saved into the `SavedModel` format, including function traces. It seems that the way you are using the `ModelCheckpoint` callback, it might only save the weights? In any case, I think it is quite reasonable to only save function traces after the training is completed, so I don't the `ModelCheckpoint` is really necessary here.

**Comment by nguerinjr** [comment] 2021-03-11 21:18
I understand your point. 

I didn't know `BackupAndRestore` checkpoints were incompatible with the others. I still need to study a bit further this callback. 

Actually, `ModelCheckpoint` also saves the function traces by default (`save_weights_only`=False). 

I am still thinking in terms of the 1.x version, I think. rsrsrsr

Therefore, if these are not problems at all, you can close the issue. I will be looking for possible problems while I implement my own architectures. 

Thanks for your explanations and your attention.

**Comment by jonycgn** [comment] 2021-03-11 21:47
Thanks for flagging the issue! It is very helpful to understand what works and what might not be working. There are still a few inconsistencies in the way TF2/Keras behaves due to the switch from TF1, so if you run into something else that doesn't seem to make sense, please let us know. It is good to discuss it.

In this case, I think there is no need to change TFC in order to make it work as intended. So I'll close this issue.

**Closed by jonycgn** 2021-03-11 21:47 UTC
