### ISSUE TITLE
Problems understanding the auxiliary loss in the entropy model

### ISSUE THREAD

**Issue by L0drik** [tensorflow/compression#20] opened 2019-05-18 17:36 UTC
Hi Ballé,

I hope it’s ok to open an issue with regards to me not understanding the logic behind a concept in the code:

In “Variational Image Compression with A Scale Hyperprior”, Appendix 6.1 you describe how to build the entropy model for the hyperprior bottleneck-layer via a learned density model. This is mostly implemented through the EntropyModel class in ‘entropy_models.py’. Inside the example script, in the training function you use the imported entropy model to get your entropy loss ‘train_bpp’  →  this part is clear.

Now to the part that I don't understand yet: During training, you also get a second loss, the auxiliary loss. **Could you describe why you need this second loss?** I’ll put my thoughts below, and would we be quite happy if anyone could correct them and/or comment on them:

---

From the code it looks like the second loss exists because we do not encode the entire bottleneck layer via range encoding, but only encode the symbols in given probability-interval [tail_mass/2, 1-tail_mass/2] via range encoding, and everything outside the interval via Golomb coding. **Why do we do that? Is it because outliers are inefficient to encode via range encoding?**

---

Given we split our symbols into a part we encode via range encoding and a part we encode via Golomb coding, then we obviously have the problem that the learned continuous PMF/CDF does not match the discrete, outlier-removed data anymore. (Reason: The CDF was trained over the entire input data). Thus, I think the second part of the build() function of the class EntropyBottleneck, line 551 to 655 in the ‘entropy_models.py’ script, is about getting the quantized PMF over the values [cdf_inverse(tail_mass/2), cdf_inverse(1-tail_mass/2)] given the continuous learned PMF over the interval [-inf, +inf].

**1. Is this correct?**

**2. Why do we need to do that at all? Can we not just cut-off the learned PMF at the desired quantiles determined by ‘tail_mass’ and then just re-normalize the remaining sum?**

Thanks for your help!

**Comment by jonycgn** [comment] 2019-05-19 01:44
Hi Chri,

you are largely correct. The reason we only model finite intervals is that the range coder requires a finite set of symbols. The reason that we try to limit that range has to do with the fact that we need to quantize the probabilities used by the range coder to a fixed precision (in the default case, 16 bits, so all symbol probabilities must add up to 65536, which corresponds to 1). If we had a very large number of symbols, this quantization would comparatively introduce a large discrepancy between the actual distribution and the one used by the range coder, which means we'd use more bit rate than necessary.

If we clipped the values to the range (which the previous version of this library did), we'd have to either accept fairly large ranges, or live with the distortion introduced by clipping. Using a fallback "universal code" improves this situation. We can keep the CDF quantization relatively precise, because we can let the range coder only handle the most frequent symbols, and we don't have to clip the values, so we get no artificial distortion. Because the values in the tails are infrequent enough, any overhead introduced by the Golomb-like code doesn't significantly contribute to the overall bit rate.

Note that this method is a general pattern that is also used by many established image/video codecs. When encoding unbounded integer values, typically only the most frequent values are range/arithmetic coded, and a Golomb-like code is used as a fallback on top of a range-coded context that uses uniform probabilities.

One note about terminology: on a continuous probability distribution, you wouldn't use the term "PMF" (probability mass function), since "mass" implies discreteness. You'd call it a density function (PDF).

Hope this helps! I'm going to close this since it's not a bug. If you have follow-up questions, please ask them in the Google group.

Best,
Johannes

**Closed by jonycgn** 2019-05-19 01:44 UTC
