### ISSUE TITLE
Problem when I tried to create a Gaussian mixture distribution

### ISSUE THREAD

**Issue by rongpan123** [tensorflow/compression#51] opened 2020-07-11 07:17 UTC
When I tried to add a Gaussian mixture distribution in entropy_models.py,  I had some problems.
1. The self._indexes in the build function of  the SymmetricConditional class:        
 def loop_body(indexes, scale):
          return indexes - tf.cast(self.scale <= scale, tf.int32)
  self._indexes = tf.foldr(
            loop_body, scale_table[:-1],
            initializer=initializer, back_prop=False, name="compute_indexes")
why the self._indexes need to subtract the scale?
2. The pmf in the build function of the SymmetricConditional class:
    upper = self._standardized_cumulative((.5 - samples) / samples_scale)
    lower = self._standardized_cumulative((-.5 - samples) / samples_scale)
    pmf = upper - lower
but there is a difference in calculating the pmf in the https://github.com/ZhengxueCheng/Learned-Image-Compression-with-GMM-and-Attention 
            pmf = (0.5 * (1 + scipy.special.erf((samples + 0.5 - mu[0]) / ((sigma[0] + TINY) * 2 ** 0.5))) - \
                  0.5 * (1 + scipy.special.erf((samples - 0.5 - mu[0]) / ((sigma[0] + TINY) * 2 ** 0.5)))) * weight[0] + \
                  (0.5 * (1 + scipy.special.erf((samples + 0.5 - mu[1]) / ((sigma[1] + TINY) * 2 ** 0.5))) - \
                  0.5 * (1 + scipy.special.erf((samples - 0.5 - mu[1]) / ((sigma[1] + TINY) * 2 ** 0.5)))) * weight[1] +\
                  (0.5 * (1 + scipy.special.erf((samples + 0.5 - mu[2]) / ((sigma[2] + TINY) * 2 ** 0.5))) - \
                  0.5 * (1 + scipy.special.erf((samples - 0.5 - mu[2]) / ((sigma[2] + TINY) * 2 ** 0.5)))) * weight[2]
the divided is scale_table in yours, and the the divided is scale in the referenced project. I'm a little confused about this. 
Could you give me some suggestions about those problems? Thank you.

**Comment by jonycgn** [comment] 2020-08-20 16:09
Hi, the loop in our code can be used to get the index into the scale table when providing an actual scale to the entropy model. It is also possible to provide the index directly. As sfor the other project, I don't know.

I'm closing this, since it is not a bug. If you have further questions, please ask in the Google group.

**Closed by jonycgn** 2020-08-20 16:09 UTC
